### PR TITLE
First commits

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR delivers the initial functionality of this repo, which is to create a group that is allowed to provision and open SSM sessions in any COOL account.

## 💭 Motivation and context ##

This access will used by COOL maintainers who need to provision and/or open SSM sessions in non-assessment environments.  A very similar repo (`cool-assessment-provisioner-iam`) allowed users to perform these actions in assessment environment accounts, but now additional access is required.  The specific use case that prompted this access is to allow COOL maintainers the ability to redeploy the certificate used by the COOL VPN server.

## 🧪 Testing ##

This code was successfully applied in Production and I verified that a user in this new group was able to successfully open an SSM session to an instance in a non-assessment environment.  I also confirmed that a user in this new group was able to successfully provision an assessment environment.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
Please update the README.

**Comment by dav3r** [comment]
> Please update the README.

Doh, thanks for catching that!  I started to make those changes last week, then got sidetracked and forgot about them.  Please see https://github.com/cisagov/cool-admin-provisioner-iam/pull/5/commits/811247a8aa139c18d7d952c00d394022a27dc53e.

**Review by jsf9k — APPROVED** [review]

**Review by jsf9k — APPROVED** [review]
You may fire at will, sir.

**Review by felddy — APPROVED** [review]
Looks great!  
I appreciate the verbose comments that find long-lost neurons of mine.

**Pull request merged**
